# -*- coding: utf-8 -*-
"""Protein_Insight_AlphaFold_Analysis.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6BmXLH4ylCruFVxZURpk--EUUY_cHQQ

# 🧬 Protein Insight — AlphaFold 구조 예측 신뢰도 분석

AlphaFold의 **PDB/mmCIF 구조 파일**과 **PAE JSON 파일**을 입력받아 단백질 구조 예측의 신뢰도를 분석하고 시각화합니다.

**분석 항목**
- 단백질 길이
- residue별 pLDDT
- 평균/최소/최대 pLDDT
- 낮은 pLDDT 구간 탐지
- PAE 평균/최대값
- PAE heatmap
- pLDDT와 PAE를 종합한 주의 영역

> ⚠️ 종합 주의 영역 판정은 이 프로젝트에서 만든 보조 분석 규칙이며 AlphaFold의 공식 판정 기준이 아닙니다.
"""

# 1. 필요한 라이브러리 설치
!pip -q install biopython numpy matplotlib pandas

# 2. 라이브러리 불러오기
import os, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

"""## 3. AlphaFold 구조 파일 업로드

**PDB 또는 mmCIF 파일 하나**를 선택하세요.

예: `AF-P14518-F1-model_v6.pdb`

"""

# 3. 구조 파일 업로드
uploaded_structure = files.upload()
structure_filename = next(iter(uploaded_structure))
print("업로드 완료:", structure_filename)

"""**① PDB/mmCIF에서 residue별 pLDDT 추출
목적**

AlphaFold 구조 파일(PDB/mmCIF)에서 각 아미노산 residue의 pLDDT 값을 추출하고, 이를 DataFrame으로 정리하여 전체 단백질의 신뢰도를 분석한다.


AlphaFold 구조 파일 → residue별 원자 정보 탐색 → B-factor에 저장된 pLDDT 추출 → residue별 평균 pLDDT 계산 → DataFrame으로 정리 → 전체 단백질 신뢰도 통계 확인
"""

# PDB/mmCIF에서 residue별 pLDDT 추출

from Bio.PDB import PDBParser, MMCIFParser

def extract_plddt(filename):
    ext = os.path.splitext(filename)[1].lower()
    if ext in [".cif", ".mmcif"]:
        parser = MMCIFParser(QUIET=True)
    elif ext == ".pdb":
        parser = PDBParser(QUIET=True)
    else:
        raise ValueError("PDB 또는 mmCIF 파일을 업로드해주세요.")

    structure = parser.get_structure("protein", filename)
    model = next(structure.get_models())

    rows = []
    for chain in model:
        for residue in chain:
            if residue.id[0] != " ":
                continue
            atoms = list(residue.get_atoms())
            if not atoms:
                continue
            plddt = float(np.mean([atom.get_bfactor() for atom in atoms]))
            rows.append({
                "chain": chain.id,
                "residue": residue.resname,
                "position": residue.id[1],
                "pLDDT": plddt
            })

    if not rows:
        raise ValueError("아미노산 residue를 찾지 못했습니다.")
    return pd.DataFrame(rows), structure

df, structure = extract_plddt(structure_filename)

print(f"단백질 길이: {len(df)} residues")
print(f"평균 pLDDT: {df.pLDDT.mean():.2f}")
print(f"최소 pLDDT: {df.pLDDT.min():.2f}")
print(f"최대 pLDDT: {df.pLDDT.max():.2f}")
display(df.head())

"""## 5. pLDDT 분석

일반적으로 pLDDT가 높을수록 해당 residue의 국소 구조 예측에 대한 신뢰도가 높습니다.

- **90 이상:** 매우 높은 신뢰도
- **70–90:** 비교적 높은 신뢰도
- **50–70:** 주의가 필요한 영역
- **50 미만:** 매우 낮은 신뢰도

② pLDDT 시각화:

residue별 pLDDT를 그래프로 나타내어 단백질 구조 예측의 신뢰도 변화를 시각적으로 확인한다.

③ 저신뢰 영역 탐색:

여러 pLDDT 기준값을 적용하여 신뢰도가 낮은 residue가 연속적으로 나타나는 구간을 자동으로 탐색한다.
"""

# pLDDT 그래프
positions = df["position"].to_numpy()
plddt = df["pLDDT"].to_numpy()

plt.figure(figsize=(14,5))
plt.plot(positions, plddt, linewidth=1.8)
plt.axhline(90, linestyle="--", label="90")
plt.axhline(70, linestyle="--", label="70")
plt.axhline(50, linestyle="--", label="50")
plt.xlabel("Residue position")
plt.ylabel("pLDDT")
plt.title("AlphaFold pLDDT by Residue")
plt.ylim(0,105)
plt.legend()
plt.grid(alpha=0.2)
plt.show()

# 낮은 pLDDT 영역 자동 탐지
def find_regions(df, threshold=70):
    positions = df["position"].tolist()
    values = df["pLDDT"].tolist()
    regions = []
    start = None
    prev = None

    for pos, value in zip(positions, values):
        if value < threshold:
            if start is None or (prev is not None and pos != prev + 1):
                if start is not None:
                    regions.append((start, prev))
                start = pos
            prev = pos
        else:
            if start is not None:
                regions.append((start, prev))
                start = None
            prev = pos

    if start is not None:
        regions.append((start, prev))
    return regions

for threshold in [90, 80, 70, 50]:
    regions = find_regions(df, threshold)
    print(f"\npLDDT < {threshold}:")
    print(regions if regions else "해당 영역 없음")

# 가장 낮은 pLDDT residue 10개
lowest = df.nsmallest(10, "pLDDT")[["chain","residue","position","pLDDT"]]
display(lowest)

"""## 9. PAE JSON 업로드

AlphaFold에서 받은 `predicted_aligned_error` JSON 파일을 업로드하세요.

예: `AF-P14518-F1-predicted_aligned_error_v6.json`

"""

# 9. PAE 파일 업로드
uploaded_pae = files.upload()
pae_filename = next(iter(uploaded_pae))
print("업로드 완료:", pae_filename)

"""① PAE JSON을 숫자 행렬로 변환 → ② PAE 통계 확인 → ③ Heatmap으로 시각화

AlphaFold의 PAE JSON에서 residue 간 예측 정렬 오차 데이터를 추출하여 행렬로 변환하고, 평균·최대 PAE를 계산한 뒤 Heatmap으로 시각화한다.
"""

# 10. PAE JSON 읽기
def load_pae(filename):
    with open(filename, "r", encoding="utf-8") as f:
        data = json.load(f)

    obj = data[0] if isinstance(data, list) else data
    matrix = np.array(obj["predicted_aligned_error"], dtype=float)
    max_pae = obj.get("max_predicted_aligned_error")
    return matrix, max_pae

pae, max_pae = load_pae(pae_filename)

print("PAE matrix shape:", pae.shape)
print(f"평균 PAE: {pae.mean():.2f} Å")
print(f"최대 PAE: {pae.max():.2f} Å")
if max_pae is not None:
    print(f"max_predicted_aligned_error: {max_pae:.2f} Å")

# 11. PAE Heatmap
plt.figure(figsize=(8,7))
plt.imshow(pae, origin="lower", cmap="viridis", aspect="auto")
plt.colorbar(label="Predicted Aligned Error (Å)")
plt.xlabel("Residue position")
plt.ylabel("Residue position")
plt.title("AlphaFold PAE Heatmap")
plt.tight_layout()
plt.show()

"""PAE 행렬에서 각 residue의 평균 PAE를 계산하여 상대적 위치 예측의 불확실성이 높은 residue를 탐색한다.

mean PAE가 높다 = 그 residue의 구조가 틀렸다는 뜻은 아님!
> 해당 residue가 다른 residue들과의 상대적인 위치 관계에서 예측 불확실성이 높다.
"""

# 12. PAE가 높은 residue 후보 탐지
mean_pae_by_residue = pae.mean(axis=1)

pae_df = pd.DataFrame({
    "position": np.arange(1, len(mean_pae_by_residue)+1),
    "mean_PAE": mean_pae_by_residue
})

display(pae_df.sort_values("mean_PAE", ascending=False).head(10))

"""## 13. pLDDT + PAE 종합 주의 영역

아래는 **이 프로젝트에서 정의한 보조 분석 규칙**입니다.

- pLDDT < 70 → 국소 구조 신뢰도가 낮은 후보
- 평균 PAE가 전체 평균보다 높음 → 상대적 위치 관계에 주의가 필요한 후보
- 두 조건이 동시에 나타나는 residue를 우선적인 **주의 영역**으로 표시

> 이것은 AlphaFold의 공식 오류 판정이 아닙니다.

pLDDT와 평균 PAE를 결합하여, 두 지표에서 동시에 상대적으로 낮은 신뢰도를 보이는 residue를 종합 주의 영역으로 선별한다.
"""

# 14. 종합 분석
if len(mean_pae_by_residue) != len(df):
    raise ValueError("PAE 길이와 구조 파일의 residue 수가 일치하지 않습니다.")

merged = df[["position","pLDDT"]].copy()
merged["mean_PAE"] = mean_pae_by_residue
pae_cutoff = merged["mean_PAE"].mean()

merged["attention"] = (
    (merged["pLDDT"] < 70) &
    (merged["mean_PAE"] > pae_cutoff)
)

attention_positions = merged.loc[merged["attention"], "position"].tolist()

print(f"전체 평균 PAE: {pae_cutoff:.2f} Å")
print("종합 주의 residue:")
print(attention_positions if attention_positions else "해당 없음")

display(merged.sort_values(["attention","pLDDT"], ascending=[False, True]).head(20))

# 15. 최종 자동 요약
mean_plddt = df["pLDDT"].mean()
min_row = df.loc[df["pLDDT"].idxmin()]
max_row = df.loc[df["pLDDT"].idxmax()]
p70_regions = find_regions(df, 70)

print("="*60)
print("🧬 Protein Insight 분석 결과")
print("="*60)
print(f"단백질 길이       : {len(df)} residues")
print(f"평균 pLDDT        : {mean_plddt:.2f}")
print(f"최저 pLDDT        : {min_row.pLDDT:.2f} (residue {int(min_row.position)})")
print(f"최고 pLDDT        : {max_row.pLDDT:.2f} (residue {int(max_row.position)})")
print(f"평균 PAE          : {pae.mean():.2f} Å")
print(f"최대 PAE          : {pae.max():.2f} Å")
print(f"pLDDT < 70 영역   : {p70_regions if p70_regions else '없음'}")
print(f"종합 주의 residue : {attention_positions if attention_positions else '없음'}")
print("="*60)

"""## 16. 해석할 때 주의할 점

이 프로그램은 AlphaFold 예측이 '맞다/틀리다'를 직접 판정하지 않습니다.

- **pLDDT**: 각 residue의 국소 구조 예측에 대한 신뢰도
- **PAE**: residue 또는 영역 사이의 상대적 위치 관계에 대한 불확실성
- pLDDT가 낮거나 PAE가 높다고 해서 반드시 구조가 틀렸다는 뜻은 아닙니다.
- 특히 PAE는 서로 다른 영역의 상대적 배치를 해석하는 데 유용합니다.

### 다음 개발 단계
1. 3D 구조 시각화
2. pLDDT에 따라 3D 구조 색상 구분
3. 특정 residue/영역 클릭 시 상세 정보 표시
4. 여러 단백질 비교
5. 실험 구조가 있는 경우 AlphaFold 예측과 비교

AlphaFold의 PDB 구조 파일을 py3Dmol을 이용해 3차원으로 시각화하여 예측된 단백질 구조를 직관적으로 확인한다.
"""

# 17. 3D 단백질 구조 시각화

!pip -q install py3Dmol

import py3Dmol

# 업로드한 PDB 파일 읽기
with open(structure_filename, "r", encoding="utf-8") as f:
    pdb_text = f.read()

# 3D viewer 생성
viewer = py3Dmol.view(width=900, height=650)

# PDB 구조 불러오기
viewer.addModel(pdb_text, "pdb")

# 단백질 구조 표시
viewer.setStyle({
    "cartoon": {
        "color": "spectrum"
    }
})

# 구조가 화면에 맞도록 조정
viewer.zoomTo()

# 흰색 배경
viewer.setBackgroundColor("white")

# 출력
viewer.show()

"""각 residue의 pLDDT를 읽어서 신뢰도 구간별로 색을 다르게 지정"""

# 19. pLDDT 수준에 따른 3D 구조 색상

viewer = py3Dmol.view(width=900, height=650)

viewer.addModel(pdb_text, "pdb")

# 기본 구조
viewer.setStyle(
    {},
    {
        "cartoon": {
            "color": "gray"
        }
    }
)

# residue별 pLDDT에 따라 색상 지정
for _, row in df.iterrows():

    pos = int(row["position"])
    score = row["pLDDT"]

    if score >= 90:
        color = "blue"

    elif score >= 70:
        color = "cyan"

    elif score >= 50:
        color = "yellow"

    else:
        color = "red"

    viewer.setStyle(
        {"resi": pos},
        {
            "cartoon": {
                "color": color
            }
        }
    )

viewer.zoomTo()
viewer.setBackgroundColor("white")
viewer.show()

"""종합 주의 영역으로 선별된 residue의 pLDDT 변화를 별도로 시각화하여 해당 영역의 신뢰도 분포를 확인한다."""

# 19. 주의 영역의 pLDDT와 평균 PAE 확인

if len(attention_detail) > 0:

    plt.figure(figsize=(12, 5))

    plt.plot(
        attention_detail["position"],
        attention_detail["pLDDT"],
        marker="o",
        label="pLDDT"
    )

    plt.axhline(
        70,
        linestyle="--",
        label="pLDDT 70"
    )

    plt.xlabel("Residue position")
    plt.ylabel("pLDDT")
    plt.title("pLDDT of Attention Region")
    plt.legend()
    plt.grid(alpha=0.2)

    plt.show()

else:

    print("종합 주의 영역이 없습니다.")

"""pLDDT와 PAE를 기반으로 선별한 종합 주의 residue를 3차원 단백질 구조에 빨간색으로 강조 표시하고 residue 번호를 부여하여 공간적 위치를 시각화한다."""

# 20. 3D 구조에 주의 residue 번호 표시

viewer = py3Dmol.view(width=900, height=650)

viewer.addModel(pdb_text, "pdb")

# 전체 구조
viewer.setStyle(
    {},
    {
        "cartoon": {
            "color": "lightgray"
        }
    }
)

# 주의 영역 강조 + residue 번호 표시
for pos in attention_positions:

    viewer.setStyle(
        {"resi": int(pos)},
        {
            "cartoon": {
                "color": "red"
            },
            "stick": {
                "color": "red"
            }
        }
    )

    viewer.addLabel(
        str(pos),
        {
            "resi": int(pos),
            "backgroundColor": "white",
            "fontColor": "black",
            "fontSize": 12
        }
    )

viewer.zoomTo()
viewer.setBackgroundColor("white")
viewer.show()

# 21. 최종 분석 요약

print("=" * 60)
print("🧬 Protein Insight - 최종 분석")
print("=" * 60)

print(f"단백질 길이      : {len(df)} residues")
print(f"평균 pLDDT       : {mean_plddt:.2f}")
print(f"최저 pLDDT       : {min_row.pLDDT:.2f}")
print(f"최저 위치        : residue {int(min_row.position)}")

print()

print(f"평균 PAE         : {pae.mean():.2f} Å")
print(f"최대 PAE         : {pae.max():.2f} Å")

print()

print(f"pLDDT < 70 영역  : {p70_regions}")
print(
    f"종합 주의 residue: "
    f"{attention_positions if attention_positions else '없음'}"
)

print("=" * 60)

# 22. residue별 pLDDT / PAE 정보 준비

residue_info = {}

for _, row in merged.iterrows():

    position = int(row["position"])

    residue_info[position] = {
        "pLDDT": float(row["pLDDT"]),
        "mean_PAE": float(row["mean_PAE"]),
        "attention": bool(row["attention"])
    }

print("residue 정보 준비 완료")
print("총 residue 수:", len(residue_info))

# 23. residue 정보가 연결된 3D 구조

viewer = py3Dmol.view(width=900, height=650)

viewer.addModel(pdb_text, "pdb")

# 기본 구조
viewer.setStyle(
    {},
    {
        "cartoon": {
            "color": "lightgray"
        }
    }
)

# pLDDT에 따른 색상
for _, row in df.iterrows():

    pos = int(row["position"])
    score = float(row["pLDDT"])

    if score >= 90:
        color = "blue"

    elif score >= 70:
        color = "cyan"

    elif score >= 50:
        color = "yellow"

    else:
        color = "red"

    viewer.setStyle(
        {"resi": pos},
        {
            "cartoon": {
                "color": color
            }
        }
    )


# 종합 주의 residue 강조
for pos in attention_positions:

    viewer.setStyle(
        {"resi": int(pos)},
        {
            "cartoon": {
                "color": "red"
            },
            "stick": {
                "color": "red"
            }
        }
    )

    viewer.addLabel(
        str(pos),
        {
            "resi": int(pos),
            "fontSize": 12,
            "backgroundColor": "white",
            "fontColor": "black"
        }
    )


viewer.zoomTo()
viewer.setBackgroundColor("white")
viewer.show()

# 24. 종합 주의 residue 상세 정보

if attention_positions:

    attention_table = merged[
        merged["position"].isin(attention_positions)
    ][
        ["position", "pLDDT", "mean_PAE", "attention"]
    ].sort_values("position")

    display(attention_table)

else:

    print("종합 주의 residue가 없습니다.")

# 25. 분석 결과 자동 해석

print("🧬 Protein Insight 자동 분석")
print()

if mean_plddt >= 90:
    print(
        f"전체 구조의 평균 pLDDT는 {mean_plddt:.2f}로, "
        "전반적으로 높은 구조 예측 신뢰도를 보입니다."
    )

elif mean_plddt >= 70:
    print(
        f"전체 구조의 평균 pLDDT는 {mean_plddt:.2f}로, "
        "전반적으로 양호한 예측 신뢰도를 보입니다."
    )

else:
    print(
        f"전체 구조의 평균 pLDDT는 {mean_plddt:.2f}로, "
        "전체적인 예측 신뢰도에 주의가 필요합니다."
    )


print()

if attention_positions:

    print(
        "pLDDT와 평균 PAE를 종합했을 때 "
        f"{attention_positions} 부근의 residue가 "
        "상대적으로 높은 불확실성을 보이는 "
        "주의 영역으로 탐지되었습니다."
    )

else:

    print(
        "설정한 기준을 동시에 만족하는 "
        "종합 주의 영역은 탐지되지 않았습니다."
    )


print()

print(
    "※ 주의 영역은 이 프로젝트에서 설정한 "
    "보조 분석 기준에 따른 결과이며, "
    "구조가 실제로 잘못되었다는 의미는 아닙니다."
)

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# # 페이지 기본 설정
# st.set_page_config(
#     page_title="Protein Insight",
#     page_icon="🧬",
#     layout="wide"
# )
# 
# # 제목
# st.title("🧬 Protein Insight")
# 
# st.subheader("AlphaFold 단백질 구조 예측 결과 분석")
# 
# st.write(
#     "AlphaFold의 구조 예측 결과를 입력하여 "
#     "pLDDT와 PAE를 기반으로 단백질 구조 예측의 신뢰도를 분석합니다."
# )
# 
# st.divider()
# 
# # 파일 업로드
# st.header("📁 분석 파일 업로드")
# 
# structure_file = st.file_uploader(
#     "① AlphaFold 구조 파일 (PDB / mmCIF)",
#     type=["pdb", "cif", "mmcif"]
# )
# 
# pae_file = st.file_uploader(
#     "② AlphaFold PAE 파일 (JSON)",
#     type=["json"]
# )
# 
# # 업로드 상태 표시
# if structure_file is not None:
#     st.success(
#         f"구조 파일 업로드 완료: {structure_file.name}"
#     )
# 
# if pae_file is not None:
#     st.success(
#         f"PAE 파일 업로드 완료: {pae_file.name}"
#     )
# 
# st.divider()
# 
# # 분석 버튼
# if structure_file is not None and pae_file is not None:
# 
#     if st.button("🔬 분석 시작", type="primary"):
#         st.info("분석 기능은 다음 단계에서 연결합니다.")

!streamlit run app.py --server.headless true > /content/streamlit.log 2>&1 &

!sleep 3
!curl -I http://localhost:8501

!pkill -f streamlit
!pkill -f cloudflared

import streamlit as st

import streamlit.components.v1 as components

components.html(
            viewer._make_html(),
            height=680
        )

!pip install -q py3Dmol

!pip install -q biopython

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import streamlit.components.v1 as components
# 
# import io
# import json
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# from Bio.PDB import PDBParser, MMCIFParser
# 
# 
# # =========================================================
# # 기본 설정
# # =========================================================
# 
# st.set_page_config(
#     page_title="Protein Insight",
#     page_icon="🧬",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# 
# # =========================================================
# # CSS
# # =========================================================
# 
# st.markdown("""
# <style>
# 
# .stApp {
#     background-color: #f7faff;
# }
# 
# .block-container {
#     max-width: 1250px;
#     padding-top: 1.5rem;
#     padding-bottom: 3rem;
# }
# 
# /* Header */
# 
# .header-title {
#     font-size: 32px;
#     font-weight: 800;
#     color: #123b78;
#     margin-bottom: 0px;
# }
# 
# .header-subtitle {
#     color: #66758a;
#     font-size: 14px;
#     margin-top: 4px;
# }
# 
# /* Cards */
# 
# .card {
#     background-color: white;
#     border-radius: 14px;
#     padding: 22px;
#     border: 1px solid #e3eaf3;
#     box-shadow: 0 2px 8px rgba(40, 70, 110, 0.06);
#     margin-bottom: 18px;
# }
# 
# /* Section */
# 
# .section-title {
#     font-size: 20px;
#     font-weight: 700;
#     color: #173b70;
#     margin-bottom: 12px;
# }
# 
# /* Description */
# 
# .description {
#     color: #66758a;
#     line-height: 1.7;
# }
# 
# /* Sidebar */
# 
# [data-testid="stSidebar"] {
#     background-color: #ffffff;
# }
# 
# [data-testid="stSidebar"] .block-container {
#     padding-top: 1.5rem;
# }
# 
# /* Metric */
# 
# [data-testid="stMetric"] {
#     background-color: white;
#     border: 1px solid #e3eaf3;
#     padding: 15px;
#     border-radius: 12px;
# }
# 
# /* Buttons */
# 
# .stButton > button {
#     border-radius: 9px;
#     font-weight: 600;
# }
# 
# /* Dataframe */
# 
# [data-testid="stDataFrame"] {
#     border-radius: 10px;
# }
# 
# /* Hide excessive top decoration */
# 
# header {
#     visibility: hidden;
# }
# 
# </style>
# """, unsafe_allow_html=True)
# 
# 
# # =========================================================
# # 세션 상태
# # =========================================================
# 
# if "analysis_done" not in st.session_state:
#     st.session_state.analysis_done = False
# 
# if "analysis_result" not in st.session_state:
#     st.session_state.analysis_result = None
# 
# 
# # =========================================================
# # 함수 1
# # 구조 파일에서 pLDDT 추출
# # =========================================================
# 
# def parse_structure(structure_file):
# 
#     file_name = structure_file.name.lower()
#     file_bytes = structure_file.getvalue()
# 
#     if file_name.endswith(".pdb"):
# 
#         parser = PDBParser(QUIET=True)
# 
#         structure = parser.get_structure(
#             "protein",
#             io.StringIO(
#                 file_bytes.decode("utf-8")
#             )
#         )
# 
#     else:
# 
#         parser = MMCIFParser(QUIET=True)
# 
#         structure = parser.get_structure(
#             "protein",
#             io.StringIO(
#                 file_bytes.decode("utf-8")
#             )
#         )
# 
#     data = []
# 
#     # 첫 번째 model만 사용
#     model = next(structure.get_models())
# 
#     for chain in model:
# 
#         for residue in chain:
# 
#             if "CA" not in residue:
#                 continue
# 
#             ca = residue["CA"]
# 
#             data.append({
#                 "chain": chain.id,
#                 "residue": residue.resname,
#                 "position": residue.id[1],
#                 "pLDDT": float(ca.get_bfactor())
#             })
# 
#     df = pd.DataFrame(data)
# 
#     return df
# 
# 
# # =========================================================
# # 함수 2
# # PAE JSON 읽기
# # =========================================================
# 
# def parse_pae(pae_file):
# 
#     pae_data = json.loads(
#         pae_file.getvalue().decode("utf-8")
#     )
# 
#     pae = np.array(
#         pae_data[0]["predicted_aligned_error"],
#         dtype=float
#     )
# 
#     max_pae = pae_data[0].get(
#         "max_predicted_aligned_error",
#         float(np.max(pae))
#     )
# 
#     return pae, max_pae
# 
# 
# # =========================================================
# # 함수 3
# # pLDDT 영역 찾기
# # =========================================================
# 
# def find_regions(df, threshold=70):
# 
#     positions = df.loc[
#         df["pLDDT"] < threshold,
#         "position"
#     ].tolist()
# 
#     if not positions:
#         return []
# 
#     regions = []
# 
#     start = positions[0]
#     previous = positions[0]
# 
#     for pos in positions[1:]:
# 
#         if pos == previous + 1:
# 
#             previous = pos
# 
#         else:
# 
#             regions.append(
#                 (int(start), int(previous))
#             )
# 
#             start = pos
#             previous = pos
# 
#     regions.append(
#         (int(start), int(previous))
#     )
# 
#     return regions
# 
# 
# # =========================================================
# # 함수 4
# # 3D 구조
# # =========================================================
# 
# def render_3d_structure(
#     structure_text,
#     file_name,
#     df,
#     attention_positions=None,
#     mode="attention"
# ):
# 
#     import py3Dmol
# 
#     viewer = py3Dmol.view(
#         width=720,
#         height=500
#     )
# 
#     # PDB / mmCIF
#     if file_name.endswith(".pdb"):
# 
#         viewer.addModel(
#             structure_text,
#             "pdb"
#         )
# 
#     else:
# 
#         viewer.addModel(
#             structure_text,
#             "mmcif"
#         )
# 
#     # -----------------------------------------------------
#     # 기본 구조
#     # -----------------------------------------------------
# 
#     viewer.setStyle(
#         {},
#         {
#             "cartoon": {
#                 "color": "lightgray"
#             }
#         }
#     )
# 
#     # -----------------------------------------------------
#     # pLDDT 색상
#     # -----------------------------------------------------
# 
#     if mode == "plddt":
# 
#         for _, row in df.iterrows():
# 
#             pos = int(row["position"])
#             score = float(row["pLDDT"])
# 
#             if score >= 90:
#                 color = "blue"
# 
#             elif score >= 70:
#                 color = "cyan"
# 
#             elif score >= 50:
#                 color = "yellow"
# 
#             else:
#                 color = "red"
# 
#             viewer.setStyle(
#                 {"resi": pos},
#                 {
#                     "cartoon": {
#                         "color": color
#                     }
#                 }
#             )
# 
#     # -----------------------------------------------------
#     # 종합 주의 residue
#     # -----------------------------------------------------
# 
#     if mode == "attention" and attention_positions:
# 
#         for pos in attention_positions:
# 
#             viewer.setStyle(
#                 {"resi": int(pos)},
#                 {
#                     "cartoon": {
#                         "color": "red"
#                     },
#                     "stick": {
#                         "color": "red"
#                     }
#                 }
#             )
# 
#             viewer.addLabel(
#                 str(pos),
#                 {
#                     "resi": int(pos),
#                     "backgroundColor": "white",
#                     "fontColor": "black",
#                     "fontSize": 11
#                 }
#             )
# 
#     viewer.zoomTo()
# 
#     viewer.setBackgroundColor(
#         "white"
#     )
# 
#     # =====================================================
#     # 핵심
#     # py3Dmol viewer를 HTML로 만들어 Streamlit에 삽입
#     # =====================================================
# 
#     components.html(
#         viewer._make_html(),
#         height=520,
#         scrolling=False
#     )
# 
# 
# # =========================================================
# # 함수 5
# # pLDDT 색상 설명
# # =========================================================
# 
# def plddt_legend():
# 
#     st.markdown(
#         """
#         <div style="
#             display:flex;
#             gap:18px;
#             flex-wrap:wrap;
#             margin-top:8px;
#             margin-bottom:10px;
#             font-size:13px;
#             color:#66758a;
#         ">
# 
#         <span>🔵 ≥ 90 매우 높은 신뢰도</span>
#         <span>🟦 70–89 높은 신뢰도</span>
#         <span>🟡 50–69 낮은 신뢰도</span>
#         <span>🔴 &lt; 50 매우 낮은 신뢰도</span>
# 
#         </div>
#         """,
#         unsafe_allow_html=True
#     )
# 
# 
# # =========================================================
# # Sidebar
# # =========================================================
# 
# with st.sidebar:
# 
#     st.markdown(
#         """
#         <div style="
#             font-size:25px;
#             font-weight:800;
#             color:#123b78;
#             margin-bottom:5px;
#         ">
#         🧬 Protein Insight
#         </div>
# 
#         <div style="
#             color:#7a8798;
#             font-size:13px;
#             margin-bottom:18px;
#         ">
#         Protein Structure Confidence Analysis
#         </div>
#         """,
#         unsafe_allow_html=True
#     )
# 
#     st.markdown("---")
# 
#     # 실제 작동하는 메뉴
#     page = st.radio(
#         "MENU",
#         [
#             "🏠 단백질 분석",
#             "📊 결과 예시",
#             "⚖️ 비교 분석",
#             "📁 자료실",
#             "ℹ️ 소개",
#             "❓ 도움말"
#         ],
#         index=0,
#         label_visibility="collapsed"
#     )
# 
#     st.markdown("---")
# 
# 
# # =========================================================
# # 소개 / 도움말 / 예시 페이지
# # =========================================================
# 
# if page == "ℹ️ 소개":
# 
#     st.markdown(
#         '<div class="header-title">Protein Insight</div>',
#         unsafe_allow_html=True
#     )
# 
#     st.markdown(
#         '<div class="header-subtitle">'
#         'Understanding Confidence in Protein Structures'
#         '</div>',
#         unsafe_allow_html=True
#     )
# 
#     st.divider()
# 
#     st.markdown("## 🧬 Protein Insight란?")
# 
#     st.write(
#         """
#         Protein Insight는 AlphaFold와 같은 단백질 구조 예측 결과를
#         단순히 시각화하는 것을 넘어, 예측 구조의 신뢰도와
#         불확실성을 함께 살펴보기 위한 분석 도구입니다.
#         """
#     )
# 
#     st.markdown("### 분석에 사용하는 지표")
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
# 
#         st.markdown(
#             """
#             <div class="card">
# 
#             <h3>pLDDT</h3>
# 
#             단백질의 각 residue 위치에서
#             구조 예측의 신뢰도를 나타냅니다.
# 
#             </div>
#             """,
#             unsafe_allow_html=True
#         )
# 
#     with col2:
# 
#         st.markdown(
#             """
#             <div class="card">
# 
#             <h3>PAE</h3>
# 
#             두 residue 사이의 상대적인
#             구조 위치 예측의 불확실성을 나타냅니다.
# 
#             </div>
#             """,
#             unsafe_allow_html=True
#         )
# 
#     st.stop()
# 
# 
# if page == "❓ 도움말":
# 
#     st.markdown(
#         '<div class="header-title">도움말</div>',
#         unsafe_allow_html=True
#     )
# 
#     st.divider()
# 
#     st.markdown("### ① 필요한 파일")
# 
#     st.write(
#         """
#         • AlphaFold 구조 파일: PDB 또는 mmCIF
#         • AlphaFold PAE 파일: JSON
#         """
#     )
# 
#     st.markdown("### ② 분석 방법")
# 
#     st.write(
#         """
#         사이드바에서 두 파일을 업로드한 뒤
#         **🔬 분석 시작** 버튼을 누르면 됩니다.
#         """
#     )
# 
#     st.markdown("### ③ 종합 주의 residue")
# 
#     st.write(
#         """
#         현재 분석에서는 pLDDT가 70 미만이고
#         residue별 평균 PAE가 전체 평균 PAE보다 높은 경우를
#         종합 주의 residue로 표시합니다.
#         """
#     )
# 
#     st.info(
#         "주의 residue는 '구조가 틀렸다'는 의미가 아니라 "
#         "예측 결과를 해석할 때 추가적인 주의가 필요한 영역이라는 의미입니다."
#     )
# 
#     st.stop()
# 
# 
# if page == "📁 자료실":
# 
#     st.markdown(
#         '<div class="header-title">📁 자료실</div>',
#         unsafe_allow_html=True
#     )
# 
#     st.divider()
# 
#     st.markdown("### 분석에 사용되는 주요 개념")
# 
#     st.markdown(
#         """
#         **pLDDT**
#         residue 단위의 구조 예측 신뢰도
# 
#         **PAE**
#         residue 사이의 상대적 위치 예측 불확실성
# 
#         **3D 구조**
#         예측된 단백질 구조를 직접 확인
# 
#         **종합 주의 영역**
#         pLDDT와 PAE를 함께 고려하여 확인하는 영역
#         """
#     )
# 
#     st.stop()
# 
# 
# if page == "📊 결과 예시":
# 
#     st.markdown(
#         '<div class="header-title">📊 분석 결과 예시</div>',
#         unsafe_allow_html=True
#     )
# 
#     st.markdown(
#         '<div class="description">'
#         '실제 파일을 업로드하면 아래와 같은 방식으로 결과가 표시됩니다.'
#         '</div>',
#         unsafe_allow_html=True
#     )
# 
#     st.divider()
# 
#     c1, c2, c3, c4 = st.columns(4)
# 
#     c1.metric("단백질 길이", "212 residues")
#     c2.metric("평균 pLDDT", "예시")
#     c3.metric("평균 PAE", "예시")
#     c4.metric("주의 residue", "예시")
# 
#     st.markdown("### 🧬 3D 구조")
# 
#     st.info(
#         "실제 분석 화면에서는 업로드한 단백질의 3D 구조가 표시됩니다."
#     )
# 
#     st.markdown("### 📈 pLDDT / PAE")
# 
#     st.info(
#         "실제 분석에서는 residue별 신뢰도와 PAE 분석 결과가 표시됩니다."
#     )
# 
#     st.stop()
# 
# 
# if page == "⚖️ 비교 분석":
# 
#     st.markdown(
#         '<div class="header-title">⚖️ 비교 분석</div>',
#         unsafe_allow_html=True
#     )
# 
#     st.markdown(
#         '<div class="description">'
#         '단백질 간 분석 결과를 비교하는 기능입니다.'
#         '</div>',
#         unsafe_allow_html=True
#     )
# 
#     st.divider()
# 
#     st.info(
#         "비교 분석 기능은 다음 단계에서 확장할 수 있습니다."
#     )
# 
#     st.stop()
# 
# 
# # =========================================================
# # 단백질 분석 페이지
# # =========================================================
# 
# st.markdown(
#     '<div class="header-title">Protein Insight</div>',
#     unsafe_allow_html=True
# )
# 
# st.markdown(
#     '<div class="header-subtitle">'
#     'Understanding Confidence in Protein Structures'
#     '</div>',
#     unsafe_allow_html=True
# )
# 
# st.divider()
# 
# 
# st.markdown(
#     "## AI가 예측한 구조, 어디까지 믿을 수 있을까?"
# )
# 
# st.markdown(
#     '<div class="description">'
#     '단백질 구조 예측 결과의 불확실성을 '
#     'pLDDT와 PAE를 이용하여 분석하는 도구입니다.'
#     '</div>',
#     unsafe_allow_html=True
# )
# 
# st.markdown("")
# 
# 
# # =========================================================
# # Sidebar 업로드
# # =========================================================
# 
# with st.sidebar:
# 
#     st.markdown("### 📤 단백질 파일 업로드")
# 
#     st.caption(
#         "AlphaFold에서 다운로드한 구조 파일을 업로드해주세요."
#     )
# 
#     structure_file = st.file_uploader(
#         "PDB / mmCIF",
#         type=["pdb", "cif", "mmcif"],
#         key="structure"
#     )
# 
#     pae_file = st.file_uploader(
#         "PAE JSON",
#         type=["json"],
#         key="pae"
#     )
# 
#     st.markdown("---")
# 
#     analyze_button = st.button(
#         "🔬 분석 시작",
#         use_container_width=True,
#         type="primary"
#     )
# 
# 
# # =========================================================
# # 업로드 상태
# # =========================================================
# 
# col1, col2 = st.columns(2)
# 
# with col1:
# 
#     st.markdown(
#         '<div class="card">',
#         unsafe_allow_html=True
#     )
# 
#     st.markdown(
#         '<div class="section-title">'
#         '📁 단백질 구조 파일'
#         '</div>',
#         unsafe_allow_html=True
#     )
# 
#     if structure_file is None:
# 
#         st.info(
#             "사이드바에서 PDB 또는 mmCIF 파일을 업로드해주세요."
#         )
# 
#     else:
# 
#         st.success(
#             f"업로드 완료: {structure_file.name}"
#         )
# 
#     st.markdown("</div>", unsafe_allow_html=True)
# 
# 
# with col2:
# 
#     st.markdown(
#         '<div class="card">',
#         unsafe_allow_html=True
#     )
# 
#     st.markdown(
#         '<div class="section-title">'
#         '📊 PAE 데이터'
#         '</div>',
#         unsafe_allow_html=True
#     )
# 
#     if pae_file is None:
# 
#         st.info(
#             "사이드바에서 PAE JSON 파일을 업로드해주세요."
#         )
# 
#     else:
# 
#         st.success(
#             f"업로드 완료: {pae_file.name}"
#         )
# 
#     st.markdown("</div>", unsafe_allow_html=True)
# 
# 
# # =========================================================
# # 분석 시작
# # =========================================================
# 
# if analyze_button:
# 
#     if structure_file is None:
# 
#         st.warning(
#             "먼저 구조 파일(PDB 또는 mmCIF)을 업로드해주세요."
#         )
# 
#         st.stop()
# 
#     if pae_file is None:
# 
#         st.warning(
#             "먼저 PAE JSON 파일을 업로드해주세요."
#         )
# 
#         st.stop()
# 
#     try:
# 
#         # -------------------------------------------------
#         # 1. 구조 분석
#         # -------------------------------------------------
# 
#         df = parse_structure(
#             structure_file
#         )
# 
#         if df.empty:
# 
#             st.error(
#                 "구조 파일에서 residue 정보를 읽지 못했습니다."
#             )
# 
#             st.stop()
# 
# 
#         # -------------------------------------------------
#         # 2. PAE 분석
#         # -------------------------------------------------
# 
#         pae, max_pae = parse_pae(
#             pae_file
#         )
# 
# 
#         # -------------------------------------------------
#         # 3. 구조와 PAE 크기 확인
#         # -------------------------------------------------
# 
#         if pae.shape[0] != len(df):
# 
#             st.error(
#                 f"""
#                 구조 파일의 residue 수({len(df)})와
#                 PAE 데이터 크기({pae.shape[0]})가
#                 일치하지 않습니다.
#                 """
#             )
# 
#             st.stop()
# 
# 
#         # -------------------------------------------------
#         # 4. 기본 pLDDT 분석
#         # -------------------------------------------------
# 
#         mean_plddt = df["pLDDT"].mean()
# 
#         min_row = df.loc[
#             df["pLDDT"].idxmin()
#         ]
# 
#         max_row = df.loc[
#             df["pLDDT"].idxmax()
#         ]
# 
# 
#         # -------------------------------------------------
#         # 5. PAE 분석
#         # -------------------------------------------------
# 
#         mean_pae = pae.mean()
# 
#         max_observed_pae = pae.max()
# 
#         mean_pae_by_residue = pae.mean(
#             axis=1
#         )
# 
# 
#         # -------------------------------------------------
#         # 6. pLDDT < 70 영역
#         # -------------------------------------------------
# 
#         p70_regions = find_regions(
#             df,
#             70
#         )
# 
# 
#         # -------------------------------------------------
#         # 7. 종합 주의 residue
#         # -------------------------------------------------
# 
#         merged = df[
#             ["position", "pLDDT"]
#         ].copy()
# 
#         merged["mean_PAE"] = (
#             mean_pae_by_residue
#         )
# 
#         pae_cutoff = (
#             merged["mean_PAE"].mean()
#         )
# 
#         merged["attention"] = (
#             (merged["pLDDT"] < 70)
#             &
#             (merged["mean_PAE"] > pae_cutoff)
#         )
# 
#         attention_positions = merged.loc[
#             merged["attention"],
#             "position"
#         ].astype(int).tolist()
# 
# 
#         # -------------------------------------------------
#         # 8. 결과 저장
#         # -------------------------------------------------
# 
#         st.session_state.analysis_result = {
#             "df": df,
#             "pae": pae,
#             "mean_plddt": mean_plddt,
#             "min_row": min_row,
#             "max_row": max_row,
#             "mean_pae": mean_pae,
#             "max_pae": max_observed_pae,
#             "mean_pae_by_residue": mean_pae_by_residue,
#             "p70_regions": p70_regions,
#             "merged": merged,
#             "attention_positions": attention_positions
#         }
# 
#         st.session_state.analysis_done = True
# 
#     except Exception as e:
# 
#         st.error(
#             "분석 중 오류가 발생했습니다."
#         )
# 
#         st.exception(e)
# 
#         st.stop()
# 
# 
# # =========================================================
# # 분석 결과 표시
# # =========================================================
# 
# if st.session_state.analysis_done:
# 
#     result = st.session_state.analysis_result
# 
#     df = result["df"]
#     pae = result["pae"]
# 
#     mean_plddt = result["mean_plddt"]
#     min_row = result["min_row"]
#     max_row = result["max_row"]
# 
#     mean_pae = result["mean_pae"]
#     max_observed_pae = result["max_pae"]
# 
#     mean_pae_by_residue = (
#         result["mean_pae_by_residue"]
#     )
# 
#     p70_regions = result["p70_regions"]
# 
#     merged = result["merged"]
# 
#     attention_positions = (
#         result["attention_positions"]
#     )
# 
# 
#     # =====================================================
#     # 분석 완료
#     # =====================================================
# 
#     st.success(
#         "분석이 완료되었습니다."
#     )
# 
# 
#     # =====================================================
#     # pLDDT 요약
#     # =====================================================
# 
#     st.markdown("## 📊 pLDDT 분석 결과")
# 
#     col1, col2, col3, col4 = st.columns(4)
# 
#     with col1:
# 
#         st.metric(
#             "단백질 길이",
#             f"{len(df)} residues"
#         )
# 
#     with col2:
# 
#         st.metric(
#             "평균 pLDDT",
#             f"{mean_plddt:.2f}"
#         )
# 
#     with col3:
# 
#         st.metric(
#             "최저 pLDDT",
#             f"{min_row['pLDDT']:.2f}"
#         )
# 
#     with col4:
# 
#         st.metric(
#             "최고 pLDDT",
#             f"{max_row['pLDDT']:.2f}"
#         )
# 
# 
#     # =====================================================
#     # pLDDT 그래프
#     # =====================================================
# 
#     st.markdown("### 🧬 Residue별 pLDDT")
# 
#     fig, ax = plt.subplots(
#         figsize=(9, 3.2)
#     )
# 
#     ax.plot(
#         df["position"],
#         df["pLDDT"],
#         linewidth=1.5
#     )
# 
#     ax.axhline(
#         70,
#         linestyle="--",
#         label="pLDDT = 70"
#     )
# 
#     ax.set_xlabel(
#         "Residue position"
#     )
# 
#     ax.set_ylabel(
#         "pLDDT"
#     )
# 
#     ax.set_title(
#         "pLDDT Confidence by Residue"
#     )
# 
#     ax.legend()
# 
#     ax.grid(
#         alpha=0.2
#     )
# 
#     st.pyplot(
#         fig,
#         use_container_width=False
#     )
# 
# 
#     # =====================================================
#     # PAE
#     # =====================================================
# 
#     st.markdown("## 📊 PAE 분석 결과")
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
# 
#         st.metric(
#             "평균 PAE",
#             f"{mean_pae:.2f} Å"
#         )
# 
#     with col2:
# 
#         st.metric(
#             "최대 PAE",
#             f"{max_observed_pae:.2f} Å"
#         )
# 
# 
#     # =====================================================
#     # PAE Heatmap
#     # =====================================================
# 
#     st.markdown("### 🔥 PAE Heatmap")
# 
#     fig, ax = plt.subplots(
#         figsize=(7, 6)
#     )
# 
#     im = ax.imshow(
#         pae,
#         origin="lower",
#         aspect="auto"
#     )
# 
#     ax.set_xlabel(
#         "Residue position"
#     )
# 
#     ax.set_ylabel(
#         "Residue position"
#     )
# 
#     ax.set_title(
#         "Predicted Aligned Error (PAE)"
#     )
# 
#     fig.colorbar(
#         im,
#         ax=ax,
#         label="PAE (Å)"
#     )
# 
#     st.pyplot(
#         fig,
#         use_container_width=False
#     )
# 
# 
#     # =====================================================
#     # Residue별 평균 PAE
#     # =====================================================
# 
#     st.markdown(
#         "### 📈 Residue별 평균 PAE"
#     )
# 
#     pae_df = pd.DataFrame({
#         "position": df["position"],
#         "mean_PAE": mean_pae_by_residue
#     })
# 
#     fig, ax = plt.subplots(
#         figsize=(9, 3.2)
#     )
# 
#     ax.plot(
#         pae_df["position"],
#         pae_df["mean_PAE"],
#         linewidth=1.5
#     )
# 
#     ax.axhline(
#         mean_pae,
#         linestyle="--",
#         label=f"전체 평균 PAE = {mean_pae:.2f} Å"
#     )
# 
#     ax.set_xlabel(
#         "Residue position"
#     )
# 
#     ax.set_ylabel(
#         "Mean PAE (Å)"
#     )
# 
#     ax.set_title(
#         "Mean PAE by Residue"
#     )
# 
#     ax.legend()
# 
#     ax.grid(
#         alpha=0.2
#     )
# 
#     st.pyplot(
#         fig,
#         use_container_width=False
#     )
# 
# 
#     # =====================================================
#     # 종합 주의 영역
#     # =====================================================
# 
#     st.markdown(
#         "## ⚠️ 종합 주의 영역"
#     )
# 
#     st.info(
#         "pLDDT < 70 이면서 residue별 평균 PAE가 "
#         "전체 평균 PAE보다 높은 residue를 "
#         "종합 주의 residue로 정의했습니다."
#     )
# 
#     if attention_positions:
# 
#         st.success(
#             f"총 {len(attention_positions)}개의 "
#             "종합 주의 residue가 확인되었습니다."
#         )
# 
#         attention_detail = merged[
#             merged["attention"]
#         ].copy()
# 
#         st.dataframe(
#             attention_detail,
#             use_container_width=True
#         )
# 
#     else:
# 
#         st.info(
#             "현재 설정한 기준을 동시에 만족하는 "
#             "residue가 없습니다."
#         )
# 
# 
#     # =====================================================
#     # 3D 구조
#     # =====================================================
# 
#     st.markdown(
#         "## 🧬 3D 단백질 구조"
#     )
# 
#     st.markdown(
#         "예측 구조에서 신뢰도가 낮거나 주의가 필요한 영역을 "
#         "3차원으로 확인할 수 있습니다."
#     )
# 
# 
#     # -----------------------------------------------------
#     # 3D 탭
#     # -----------------------------------------------------
# 
#     tab1, tab2 = st.tabs(
#         [
#             "🎨 pLDDT 신뢰도",
#             "⚠️ 종합 주의 영역"
#         ]
#     )
# 
# 
#     structure_text = (
#         structure_file.getvalue()
#         .decode("utf-8")
#     )
# 
#     file_name = (
#         structure_file.name.lower()
#     )
# 
# 
#     with tab1:
# 
#         plddt_legend()
# 
#         render_3d_structure(
#             structure_text,
#             file_name,
#             df,
#             attention_positions=[],
#             mode="plddt"
#         )
# 
# 
#     with tab2:
# 
#         if attention_positions:
# 
#             render_3d_structure(
#                 structure_text,
#                 file_name,
#                 df,
#                 attention_positions,
#                 mode="attention"
#             )
# 
#         else:
# 
#             st.info(
#                 "종합 주의 residue가 없어 "
#                 "전체 구조를 표시합니다."
#             )
# 
#             render_3d_structure(
#                 structure_text,
#                 file_name,
#                 df,
#                 [],
#                 mode="attention"
#             )
# 
# 
#     # =====================================================
#     # 최저 pLDDT residue
#     # =====================================================
# 
#     st.markdown(
#         "## ⚠️ 가장 낮은 pLDDT residue"
#     )
# 
#     st.dataframe(
#         df.nsmallest(
#             10,
#             "pLDDT"
#         ).reset_index(drop=True),
#         use_container_width=True
#     )
# 
# 
#     # =====================================================
#     # 최종 분석 요약
#     # =====================================================
# 
#     st.markdown(
#         "## 🧾 최종 분석 요약"
#     )
# 
#     st.markdown(
#         f"""
#         <div class="card">
# 
#         <b>단백질 길이</b>
#         {len(df)} residues
# 
#         <br><br>
# 
#         <b>평균 pLDDT</b>
#         {mean_plddt:.2f}
# 
#         <br><br>
# 
#         <b>최저 pLDDT</b>
#         {min_row['pLDDT']:.2f}
#         (residue {int(min_row['position'])})
# 
#         <br><br>
# 
#         <b>평균 PAE</b>
#         {mean_pae:.2f} Å
# 
#         <br><br>
# 
#         <b>최대 PAE</b>
#         {max_observed_pae:.2f} Å
# 
#         <br><br>
# 
#         <b>pLDDT &lt; 70 영역</b>
#         {p70_regions if p70_regions else "없음"}
# 
#         <br><br>
# 
#         <b>종합 주의 residue</b>
#         {attention_positions if attention_positions else "없음"}
# 
#         </div>
#         """,
#         unsafe_allow_html=True
#     )
# 
# 
# else:
# 
#     # =====================================================
#     # 분석 전 화면
#     # =====================================================
# 
#     st.markdown(
#         """
#         <div class="card">
# 
#         <div class="section-title">
#         🧬 Protein Insight에 오신 것을 환영합니다
#         </div>
# 
#         <div class="description">
# 
#         AlphaFold 구조 예측 결과의 신뢰도를
#         pLDDT와 PAE를 이용하여 분석합니다.
# 
#         <br><br>
# 
#         왼쪽 사이드바에서 구조 파일과 PAE JSON을
#         업로드한 뒤 <b>🔬 분석 시작</b>을 눌러주세요.
# 
#         </div>
# 
#         </div>
#         """,
#         unsafe_allow_html=True
#     )
# 
#     col1, col2, col3 = st.columns(3)
# 
#     with col1:
# 
#         st.markdown(
#             """
#             <div class="card">
# 
#             <h3>📊 pLDDT</h3>
# 
#             residue별 구조 예측
#             신뢰도를 확인합니다.
# 
#             </div>
#             """,
#             unsafe_allow_html=True
#         )
# 
#     with col2:
# 
#         st.markdown(
#             """
#             <div class="card">
# 
#             <h3>🔥 PAE</h3>
# 
#             residue 사이의
#             상대적 위치 예측 불확실성을 확인합니다.
# 
#             </div>
#             """,
#             unsafe_allow_html=True
#         )
# 
#     with col3:
# 
#         st.markdown(
#             """
#             <div class="card">
# 
#             <h3>🧬 3D Structure</h3>
# 
#             예측된 단백질 구조와
#             주의 영역을 3차원으로 확인합니다.
# 
#             </div>
#             """,
#             unsafe_allow_html=True
#         )
# 
# 
# # =========================================================
# # Footer
# # =========================================================
# 
# st.divider()
# 
# st.markdown(
#     """
#     <div style="
#         text-align:center;
#         color:#718096;
#         font-size:13px;
#         padding:10px;
#     ">
# 
#     From Experiment to Insight　|
#     AlphaFold 구조 예측 결과를 보다 정확하게 해석하기 위한 도구
# 
#     </div>
#     """,
#     unsafe_allow_html=True
# )

!pkill -f streamlit
!streamlit run app.py > /content/streamlit.log 2>&1 &

!curl -I http://localhost:8501

!pkill -f cloudflared

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

!cloudflared --version

!cloudflared tunnel --url http://localhost:8501